defaultPortal: hubspotonearth
portals:
  - name: hubspotonearth
    portalId: 5357708
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COqF96KzMBIIAA0ADAAA4AEYjIHHAiDT-bgDKO7pDDIUpDNdaBAqpoKxW7W7MXjePDpr91k6NwAABEEAAAB4AAAAAAAAAACAAQAAAAAABMAAwAdg_v8xAAAAAAAAAGAAAAAAAAAAAAAAAAAAwAFCFKNQViXGZqZe0UFnAJ86yFk175InSgNuYTFSAFoA
        expiresAt: '2022-09-13T01:01:43.534Z'
    personalAccessKey: >-
      CiQyMzMyZTY3Yi02ZTkyLTRkZDctOGQxOC00ODJjMzM0ODUzNjkQjIHHAhjT-bgDKhkABeaRgoGQECQfzghuyzzy-dPQerJHMVjP
