defaultPortal: hubspotonearth
portals:
  - name: hubspotonearth
    portalId: 5357708
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPzn_pWzMBIIAA0ADAAA4AEYjIHHAiDT-bgDKO7pDDIU2MbIOIut_C4hSmF6gnYFda79-sM6NwAABEEAAAB4AAAAAAAAAACAAQAAAAAABMAAwAdg_v8xAAAAAAAAAGAAAAAAAAAAAAAAAAAAwAFCFHj6Y_GaCVTt25LwzpNdFRkily1wSgNuYTFSAFoA
        expiresAt: '2022-09-12T17:29:27.806Z'
    personalAccessKey: >-
      CiQyMzMyZTY3Yi02ZTkyLTRkZDctOGQxOC00ODJjMzM0ODUzNjkQjIHHAhjT-bgDKhkABeaRgoGQECQfzghuyzzy-dPQerJHMVjP
