defaultPortal: hubspotonearth
portals:
  - name: hubspotonearth
    portalId: 5357708
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CO71092aLxIIAA0ADAAA4AEYjIHHAiDT-bgDKO7pDDIZAG3oVvjR8PpS03d6dHj0Z_veg0cny4PFDTooAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zEAAAAAAAAAYEIZAG3oVvgNnm_LGutqDIlu4zkDOK57FX9VwkoDbmEx
        expiresAt: '2021-05-27T02:43:55.252Z'
    personalAccessKey: >-
      CiQyMzMyZTY3Yi02ZTkyLTRkZDctOGQxOC00ODJjMzM0ODUzNjkQjIHHAhjT-bgDKhkABeaRgoGQECQfzghuyzzy-dPQerJHMVjP
